- import_playbook: mapr-include-vars.yml
- name: Setup Zookeeper String
  hosts: all
  roles:
    - ../roles/mapr-configure-vars-zk
- name: Setup Hive Variables
  hosts: all
  vars:
      num_mysql_hosts: "{{ groups['ext_mysql']|length }}"
  roles:
    - ../roles/mapr-hive-vars
- name: Install Spark on YARN
  hosts: mapr_spark_yarn
  roles:
    - ../roles/mapr-spark-yarn-install
- name: Uninstall Spark on YARN
  hosts: all:!mapr_spark_yarn
  roles:
    - ../roles/mapr-spark-yarn-uninstall
- name: Install Spark Thrift Server
  hosts: mapr_spark_thriftserver
  roles:
    - ../roles/mapr-spark-thriftserver-install
- name: Uninstall Spark Thrift Server
  hosts: all:!mapr_spark_thriftserver
  roles:
    - ../roles/mapr-spark-thriftserver-uninstall
- name: Install Spark History Server
  hosts: mapr_spark_historyserver
  roles:
    - ../roles/mapr-spark-historyserver-install
- name: Uninstall Spark History Server
  hosts: all:!mapr_spark_historyserver
  roles:
    - ../roles/mapr-spark-historyserver-uninstall
- name: Get Spark Shuffle Sort JAR from first Spark node
  hosts: mapr_spark_yarn[0]
  roles:
    - {role: ../roles/mapr-spark-yarn-shuffle-retrieve, when: yarn_spark_shuffle }
- name: Upload Spark Shuffle Sort JAR to all YARN node managers
  hosts: mapr_nodemanager
  roles:
    - {role: ../roles/mapr-spark-yarn-shuffle-distribute, when: yarn_spark_shuffle }
